version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
formats:
  - pdf
sphinx:
   configuration: doc/conf.py
python:
 install:
  - method: pip
    path: .
  - method: setuptools
    path: .
conda:
  environment: environment.yml
