version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
formats:
  - pdf
sphinx:
   configuration: doc/conf.py
python:
 install:
  - method: setuptools
    path: .
conda:
  environment: environment.yml
