version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - gfortran
conda:
  environment: environment.yml
python:
  install:
    - method: pip
      path: .
formats:
  - pdf
sphinx:
   configuration: doc/conf.py
