version: 2
formats:
  - pdf
sphinx:
   configuration: doc/conf.py
python:
   version: "3.7"
   install:
   - requirements: requirements.txt
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
conda:
  environment: environment.yml
