version: 2
formats:
  - pdf
sphinx:
   configuration: doc/conf.py
python:
 version: "3.7"
 install:
  - method: pip
    path: .
   - requirements: requirements.txt
conda:
  environment: environment.yml
