name: VolterraBasis
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - xarray
  - scikit-learn
  - scikit-fem
  - sparse
  - libgfortran-ng
  - sphinx-gallery
  - numpydoc
  - joblib
