name: VolterraBasis
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - xarray
  - compilers
  - libgfortran-ng
  - sphinx-gallery
  - numpydoc
  - liblapack
  - sphinx-autoapi
